import { Job, ScreeningQuestion } from "./types";

export const mockJobs: Job[] = [
  {
    id: "job-001",
    title: "Software Engineer",
    company: "Confidential",
    location: "San Francisco, CA",
    description:
      "A major enterprise client and our company partnership — our company builds AI agents trusted by the largest B2C companies in the world. Industry leaders trust our company with their most complex support and operations workflows across voice, chat, and email.\n\nYou'll contribute to projects across our stack, including Atlas (our AI assistant), Activity Stream (log visualization), Dynamic Knowledge, and Agent Memory.",
    responsibilities: [
      "Build features for our AI assistant: charts and alerts in Slack, natural language queries, and expanding Atlas to manage platform resources",
      "Implement Activity Stream: log visualization with filters, timestamps, and frequency charts",
      "Add time-based dynamic knowledge that auto-updates from sources like status pages",
      "Build agent memory: conversation awareness and recent interaction lookups",
      "Own smaller projects end-to-end while pairing with senior engineers on larger initiatives",
    ],
    requirements: [
      "You'll contribute to projects across our stack",
      "Atlas: Building features for our AI assistant",
      "Activity Stream: Log visualization with filters, timestamps, and frequency charts",
      "Dynamic knowledge: Adding time-based knowledge that auto-updates",
      "Agent memory: Conversation awareness and recent interaction lookups",
      "Ability to be paired with senior engineers on larger initiatives while owning smaller projects end-to-end",
    ],
    preferred_qualifications: [
      "Experience with AI or conversational agent systems",
      "Familiarity with Slack API integrations",
    ],
    salary_min: 130000,
    salary_max: 160000,
    job_type: "onsite",
    category: "Engineering",
    posted_date: "2026-03-15",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-15",
    certification_tier: "core",
    skill_categories: ["backend", "ai_agents"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Learning budget"],
  },
  {
    id: "job-002",
    title: "Software Engineer, Fullstack",
    company: "Confidential",
    location: "New York, NY",
    description:
      "As an Early Career Software Engineer, you'll help shape core user experiences and accelerate how people discover value in our product. You'll tackle meaningful challenges with increasing autonomy, crafting code that millions of users will experience.\n\nYou'll take ownership of projects that matter, make critical technical decisions, and contribute your unique perspective to our product vision.",
    responsibilities: [
      "Plan, build, and ship product features from conception to launch, then iterate based on insights and user feedback",
      "Improve performance, reliability, and quality of key experiences used by millions of users",
      "Run experiments that drive activation, retention, collaboration, and revenue",
      "Build internal tools and platform improvements that help all engineers ship quickly and safely",
      "Contribute to team norms, code quality, and a culture of learning and thoughtful tradeoffs",
    ],
    requirements: [
      "Plan, build, and ship product features from conception to launch",
      "Improve performance, reliability, and quality of key experiences",
      "Run experiments that drive activation, retention, collaboration, and revenue",
      "Build internal tools and platform improvements",
      "Contribute to team norms, code quality, and a culture of learning",
    ],
    preferred_qualifications: [
      "Experience working on consumer-facing products at scale",
      "Background in data science or analytics",
    ],
    salary_min: 120000,
    salary_max: 150000,
    job_type: "onsite",
    category: "Engineering",
    posted_date: "2026-03-14",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "entry",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-14",
    certification_tier: "core",
    skill_categories: ["fullstack", "typescript"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Flexible PTO"],
  },
  {
    id: "job-003",
    title: "Senior Software Engineer – Backend",
    company: "Confidential",
    location: "Remote",
    description:
      "Work closely with product managers and other stakeholders to define and implement new features that meet product and customer needs. Write clean, maintainable and efficient code. Develop automated tests to ensure quality and reliability of the codebase.",
    responsibilities: [
      "Collaborate with product managers and other stakeholders to define and implement new features",
      "Write clean, maintainable and efficient code",
      "Develop automated tests to ensure quality and reliability of the codebase",
      "Troubleshoot and resolve production issues",
      "Mentor junior engineers and conduct code reviews",
    ],
    requirements: [
      "5+ years of experience with extensive experience in software engineering",
      "Prior experience with cross-functional collaboration, communication and project management",
      "Demonstrated leadership skills and the ability to mentor and guide junior engineers",
      "Ability to work with operations, product, design, and data science",
      "Proven track record of shipping successful projects at scale",
    ],
    preferred_qualifications: [
      "Experience with distributed systems",
      "Familiarity with cloud infrastructure (AWS, GCP, or Azure)",
    ],
    salary_min: 170000,
    salary_max: 220000,
    job_type: "remote",
    category: "Engineering",
    posted_date: "2026-03-13",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "senior",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-13",
    certification_tier: "core_plus",
    skill_categories: ["backend", "distributed_systems"],
    source_url: "#",
    benefits: ["Remote-first", "Health insurance", "Equity"],
  },
  {
    id: "job-004",
    title: "Senior Software Engineer, Ad Technology",
    company: "Confidential",
    location: "Seattle, WA",
    description:
      "A highly scalable and highly available real-time advertising platform is crucial for supporting and growing our advertising business. The Ad Engineering Team's mission is to build this platform. We are hiring a Senior Software Engineer for the Advertising Platform to play a vital role in this mission.",
    responsibilities: [
      "Work alongside a highly skilled engineering team to design, develop, and maintain large-scale, highly performing, real-time applications",
      "Own building features, driving directly with the product and other engineering teams",
      "Be an evangelist for best practices across all functions – developers, QA, and infrastructure/ops",
      "Be an evangelist for platform innovation and reuse",
      "Deliver top-quality software in a timely fashion",
    ],
    requirements: [
      "Work alongside a highly skilled engineering team on real-time applications",
      "Own building features and driving directly with product teams",
      "Demonstrate excellent communication skills with technical and non-technical audiences",
      "Evangelize best practices across all functions",
      "Deliver top-quality software in a timely fashion",
      "Experience with large-scale, high-performance systems",
    ],
    preferred_qualifications: [
      "Experience with real-time bidding systems",
      "Knowledge of ad tech ecosystem and programmatic advertising",
    ],
    salary_min: 180000,
    salary_max: 230000,
    job_type: "onsite",
    category: "Engineering",
    posted_date: "2026-03-12",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "senior",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-12",
    certification_tier: "core_plus",
    skill_categories: ["backend", "ad_tech", "real_time_systems"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Relocation support"],
  },
  {
    id: "job-005",
    title: "Software Engineer – Frontend",
    company: "Confidential",
    location: "Remote",
    description:
      "Our approach to flexible work is centered on trust and optimized for culture, connection, clarity, and the evolving needs of our business. The work location of this role is hybrid, meaning it will be performed both from home and from our office on select days.",
    responsibilities: [
      "Design and develop user-facing features in JavaScript/TypeScript",
      "Write clean, efficient code using modern frameworks like Angular, Ember, or React",
      "Debug and optimize frontend performance",
      "Collaborate with design and backend teams on new product features",
      "Maintain and improve frontend test coverage",
    ],
    requirements: [
      "BA/BS in Computer Science or related technical field or equivalent practical experience",
      "1+ years of industry experience in software design, development, and algorithm related solutions",
      "Experience programming in languages such as Javascript, HTML, CSS, Python, Java",
      "Experience writing clean JavaScript including experience with modern frameworks (Angular/Ember/React)",
      "Debugging tools experience (Chrome Dev Tools, etc.)",
      "Expert-level knowledge of Ember preferred",
    ],
    preferred_qualifications: [
      "MS or PhD in Computer Science or related technical discipline",
      "Expert-level knowledge of Ember",
      "Experience with design systems",
    ],
    salary_min: 140000,
    salary_max: 180000,
    job_type: "remote",
    category: "Engineering",
    posted_date: "2026-03-11",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-11",
    certification_tier: "core",
    skill_categories: ["frontend", "react", "javascript"],
    source_url: "#",
    benefits: ["Remote-first", "Health insurance", "Home office stipend"],
  },
  {
    id: "job-006",
    title: "Backend Software Engineer",
    company: "Confidential",
    location: "Los Angeles, CA",
    description:
      "Collaborate across our Engineering team on the expansion of our service platform. Develop and operate scalable and resilient distributed services that run on Amazon Web Services (AWS). Build large scale distributed systems that handle billions of data events a day.",
    responsibilities: [
      "Collaborate across our Engineering team on the expansion of our service platform",
      "Develop and operate scalable and resilient distributed services on AWS",
      "Build large scale distributed systems handling billions of data events a day",
      "Write unit and integration tests",
      "Apply cutting-edge Generative AI tools in real-world engineering work",
    ],
    requirements: [
      "Collaborate across Engineering on the expansion of our service platform",
      "Develop and operate scalable and resilient distributed services on AWS",
      "Build large scale distributed systems that handle billions of data events a day",
      "Write unit and integration tests",
      "Access to cutting-edge Generative AI tools",
      "Relevant project experience (hackathons, personal projects, GitHub, Open Source)",
    ],
    preferred_qualifications: [
      "Experience with AWS services (Lambda, ECS, RDS, Kinesis)",
      "Familiarity with Generative AI and LLM integrations",
    ],
    salary_min: 140000,
    salary_max: 175000,
    job_type: "onsite",
    category: "Engineering",
    posted_date: "2026-03-10",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-10",
    certification_tier: "core",
    skill_categories: ["backend", "aws", "distributed_systems"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Learning budget"],
  },
  {
    id: "job-007",
    title: "Product Manager",
    company: "Confidential",
    location: "New York, NY",
    description:
      "Define success, prioritize problems, and identify the best strategies considering wider organizational and company context. Adapt and adjust strategies to reflect learnings and changes in context. Identify and drive consensus for how to prioritize and realize the most significant opportunities in your product area.",
    responsibilities: [
      "Define success and prioritize problems with the best strategies given organizational context",
      "Adapt and adjust strategies to reflect learnings and changes in context",
      "Identify and drive consensus for how to prioritize the most significant opportunities",
      "Work with a cross-functional team to define a product vision and develop a roadmap",
      "Drive progress against goals and communicate clearly across stakeholders",
    ],
    requirements: [
      "8+ years of relevant industry experience with at least 3 years in Product Management",
      "Bachelor's degree (STEM subject ideal): Computer Science, Engineering, Information Systems, Analytics, Mathematics, or Physics",
      "Proven experience to drive a step change in the performance of a product",
      "Extensive understanding in analyzing large scale, complex data sets",
      "Experience integrating a diverse set of requirements from a broad set of users",
      "Demonstrated experience in communication, bringing extreme clarity to complex messages",
    ],
    preferred_qualifications: [
      "Experience with enterprise or B2B software products",
      "Familiarity with data analytics tools (Mixpanel, Amplitude, etc.)",
    ],
    salary_min: 160000,
    salary_max: 200000,
    job_type: "onsite",
    category: "Product",
    posted_date: "2026-03-15",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "senior",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-15",
    certification_tier: "core_plus",
    skill_categories: ["product_management", "strategy"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Flexible PTO"],
  },
  {
    id: "job-008",
    title: "Senior Product Manager",
    company: "Confidential",
    location: "Remote",
    description:
      "The Senior Product Manager for our customer support platform collaborates across Product Operations, Finance, Engineering, Retail, and Sales teams to define the roadmap and launch new device protection service experiences for our customer support platform.",
    responsibilities: [
      "Collaborate across Product Operations, Finance, Engineering, Retail, and Sales to define the roadmap",
      "Launch new device protection service experiences for our customer support platform",
      "Manage full product lifecycle from concept to launch",
      "Simplify operational and financial complexity into clear product strategies",
      "Influence through storytelling, data, and collaboration",
    ],
    requirements: [
      "6+ years in product management and/or product marketing, including full product lifecycle ownership",
      "Demonstrated success working cross-functionally with operations, finance, legal, engineering, and marketing",
      "10+ years in product management preferred",
      "Experience with device protection programs, warranty or service operations",
      "Ability to simplify operational and financial complexity into clear product strategies",
      "Excellent written and verbal communication skills",
    ],
    preferred_qualifications: [
      "Experience with post-purchase services models such as repair, claims, and customer support",
      "Background in consumer electronics or retail tech",
    ],
    salary_min: 190000,
    salary_max: 240000,
    job_type: "remote",
    category: "Product",
    posted_date: "2026-03-14",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "senior",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-14",
    certification_tier: "advanced",
    skill_categories: ["product_management", "operations"],
    source_url: "#",
    benefits: ["Remote-first", "Health insurance", "Equity", "Wellness stipend"],
  },
  {
    id: "job-009",
    title: "Associate Product Manager",
    company: "Confidential",
    location: "Remote",
    description:
      "We are a Flex First team. There's no one-size fits all approach to how we do our best work. Our employees have the flexibility to choose where they do their best work — whether it's from home, an office, or your favorite coffee shop — while staying connected and building community through regular in-person events.",
    responsibilities: [
      "Exhibit deep passion for technology and product design",
      "Develop product solutions for customer pain points",
      "Influence and empower diverse cross-functional teams",
      "Collaborate with engineering, design, and data teams on product initiatives",
      "Contribute to product roadmap discussions and prioritization",
    ],
    requirements: [
      "Deep passion for technology and product design from a technical degree, personal projects, or experience",
      "Demonstrated ability to come up with product solutions for customer pain points",
      "Leadership potential and natural ability to influence and empower diverse teams",
      "Strong analytical and communication skills",
      "Ability to work effectively in a remote, flex-first environment",
    ],
    preferred_qualifications: [
      "Technical background in CS or engineering",
      "Experience with product analytics tools",
    ],
    salary_min: 120000,
    salary_max: 155000,
    job_type: "remote",
    category: "Product",
    posted_date: "2026-03-13",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "entry",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-13",
    certification_tier: "core",
    skill_categories: ["product_management"],
    source_url: "#",
    benefits: ["Remote-first", "Health insurance", "Learning budget"],
  },
  {
    id: "job-010",
    title: "Product Manager, Growth",
    company: "Confidential",
    location: "New York, NY",
    description:
      "On our team, you'll find an environment that champions kindness and respect, values diverse perspectives, and upholds inclusivity at every turn. We believe that every member of our team adds invaluable insights and abilities. In our pursuit of excellence, we foster a culture of trust and integrity, collaboration, and mutual growth.",
    responsibilities: [
      "Manage multiple product workstreams and follow structured processes",
      "Test APIs and review API responses to ensure integrations work correctly",
      "Work with configuration files (YAML/JSON) and perform basic technical troubleshooting",
      "Collaborate with fintech, capital markets, and SaaS product teams",
      "Define and track growth metrics across product lines",
    ],
    requirements: [
      "2–3 years of experience in Product Management, Project Management, Business Analysis, or a related role (preferably in fintech, capital markets, or SaaS)",
      "Ability to manage multiple workstreams and follow structured processes",
      "Comfortable testing APIs (e.g., Postman) and reviewing API responses",
      "Familiarity with configuration files (YAML/JSON) and basic technical troubleshooting",
      "Detail-oriented, proactive, and collaborative",
      "Exposure to trading systems or financial technology preferred",
    ],
    preferred_qualifications: [
      "Experience in fintech or capital markets",
      "Familiarity with trading systems or financial platforms",
    ],
    salary_min: 145000,
    salary_max: 185000,
    job_type: "onsite",
    category: "Product",
    posted_date: "2026-03-12",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-12",
    certification_tier: "core",
    skill_categories: ["product_management", "growth", "fintech"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Flexible PTO"],
  },
  {
    id: "job-011",
    title: "Junior UI/UX Designer",
    company: "Confidential",
    location: "Remote",
    description:
      "Created in 2016, we have always taken a market-leading and collaborative approach to cloud deployment and management. Our product roadmap is greatly influenced by regular feedback from customers. Today, we are used in over 50 countries by more than 15,000 organizations of every size and vertical.",
    responsibilities: [
      "Collaborate with product managers, developers, and other designers to maintain and evolve design systems",
      "Create wireframes, mockups, and interactive prototypes",
      "Support accessibility and usability practices",
      "Improve designs based on internal and external feedback",
      "Participate in user research, testing, and feedback sessions",
    ],
    requirements: [
      "Collaborate with product managers, developers, and other designers to maintain and evolve design systems",
      "Create wireframes, mockups, and interactive prototypes",
      "Support accessibility and usability practices",
      "Improve designs and systems based on feedback",
      "Participate in user research, testing, and feedback sessions",
      "Create and maintain UI component libraries",
    ],
    preferred_qualifications: [
      "Experience with Figma or Sketch",
      "Knowledge of WCAG accessibility standards",
    ],
    salary_min: 80000,
    salary_max: 110000,
    job_type: "remote",
    category: "Design",
    posted_date: "2026-03-15",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "entry",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-15",
    certification_tier: "core",
    skill_categories: ["ui_design", "ux_design", "figma"],
    source_url: "#",
    benefits: ["Remote-first", "Health insurance", "Equipment budget"],
  },
  {
    id: "job-012",
    title: "Senior UX Designer",
    company: "Confidential",
    location: "Austin, TX",
    description:
      "You are equal parts systems thinker and craft-driven designer. You bring clarity to complex ecosystems, translating identity frameworks, account services, safety policies, and platform technologies into seamless, intuitive player experiences. You leverage emerging capabilities to design secure, scalable solutions that build trust across regions and devices.",
    responsibilities: [
      "Translate complex identity and safety frameworks into seamless, intuitive user experiences",
      "Design secure, scalable solutions that build trust across regions and devices",
      "Ground every decision in research, experimentation, and measurable outcomes",
      "Thrive in ambiguity, defining structure and process where needed",
      "Partner with cross-functional teams to ship platform-level UX",
    ],
    requirements: [
      "BA/BS in Interaction or Product Design, Human Factors, or equivalent experience",
      "5+ years of product or UX design experience, including platform or systems-level work",
      "A portfolio that showcases thoughtful, simple, deliberate and intuitive design with extraordinary interaction, motion, and visuals",
      "Experience shipping complex, multi-surface experiences (console, mobile, web, or connected devices)",
      "Ability to operate independently in ambiguous, technical environments",
    ],
    preferred_qualifications: [
      "Experience with multi-platform design systems",
      "Background in safety or trust UX patterns",
    ],
    salary_min: 130000,
    salary_max: 165000,
    job_type: "onsite",
    category: "Design",
    posted_date: "2026-03-14",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "senior",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-14",
    certification_tier: "core_plus",
    skill_categories: ["ux_design", "product_design", "systems_thinking"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Learning budget"],
  },
  {
    id: "job-013",
    title: "Product Designer",
    company: "Confidential",
    location: "San Francisco, CA",
    description:
      "This role will be based in Mountain View or San Francisco. Our approach to flexible work is centered on trust and optimized for culture, connection, clarity, and the evolving needs of our business. Our global Product Design team is working to create economic opportunity for every member of the global workforce.",
    responsibilities: [
      "Design end-to-end product flows from concept through final polish",
      "Participate in the complete product development lifecycle of web and/or software applications",
      "Deliver small to medium-scale projects independently",
      "Influence decisions on assigned projects by actively engaging and adding value",
      "Partner with product managers and engineers on user experience from conception through launch",
    ],
    requirements: [
      "BA/BS degree in graphic design, design communication, human-computer interaction, or related field",
      "Experience participating in the complete product development lifecycle",
      "2+ years of experience in user experience design or industry experience",
      "Ability to deliver small to medium-scale projects independently",
      "Ability to influence decisions on assigned projects",
      "Ability to deliver solutions for structured problems with few dependencies",
    ],
    preferred_qualifications: [
      "Experience with design systems and component libraries",
      "Familiarity with accessibility best practices",
    ],
    salary_min: 150000,
    salary_max: 195000,
    job_type: "onsite",
    category: "Design",
    posted_date: "2026-03-13",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-13",
    certification_tier: "core",
    skill_categories: ["product_design", "figma", "ux_design"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Catered meals"],
  },
  {
    id: "job-014",
    title: "Senior Product Designer",
    company: "Confidential",
    location: "New York, NY",
    description:
      "Design flows and experiences that are incredibly simple and elegant for our supported platforms. Design new experiences or layouts that evolve or define visual systems. Give and solicit feedback from other designers in order to continually raise our bar for quality.",
    responsibilities: [
      "Design flows and experiences that are incredibly simple and elegant",
      "Design new experiences or layouts that evolve or define visual systems",
      "Give and solicit feedback from other designers to continually raise quality",
      "Partner with product managers, engineers, UX researchers and content strategists",
      "Oversee the user experience of a product from conception until launch",
    ],
    requirements: [
      "Give and solicit feedback from other designers to continually raise the bar for quality",
      "Partner with product managers, engineers, UX researchers and content strategists",
      "Bachelor's degree in Design, Human-Computer Interaction, Computer Science, or a related field",
      "2+ years designing software products focusing on user experience, interaction, and visual design",
      "Familiarity with prototyping tools and building low-fidelity mockups",
      "Experience showcasing end-to-end design process across multiple projects",
    ],
    preferred_qualifications: [
      "Experience with motion design and micro-interactions",
      "Background in mobile design (iOS/Android)",
    ],
    salary_min: 165000,
    salary_max: 205000,
    job_type: "onsite",
    category: "Design",
    posted_date: "2026-03-12",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "senior",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-12",
    certification_tier: "core_plus",
    skill_categories: ["product_design", "visual_design", "ux_design"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Learning budget"],
  },
  {
    id: "job-015",
    title: "Marketing Operations Manager",
    company: "Confidential",
    location: "New York, NY",
    description:
      "You're always thinking about how to improve your community's future. You're passionate about building a global community where everyone can feel seen and inspired. Flexible and ready to get the job done, but humble and thoughtful. You strive for quality, have fun doing it, and always have the greater good of the company in mind.",
    responsibilities: [
      "Coordinate market launches and activations",
      "Project manage marketing needs for campaigns and launches in local markets",
      "Support teams in adapting global campaigns to fit local market needs",
      "Ensure marketing materials, messaging, and activations are delivered on time and aligned with the brand",
      "Serve as the main point of contact between Global Marketing and local market teams",
    ],
    requirements: [
      "Coordinate Market Launches and Activations",
      "Project manage marketing needs for campaigns and launches in local markets",
      "Support teams in adapting global campaigns to fit local market needs",
      "Ensure marketing materials, messaging, and activations are delivered on time and aligned with the brand",
      "Global–Local Coordination experience",
      "Serve as the main point of contact between Global Marketing and local market teams",
    ],
    preferred_qualifications: [
      "Experience with marketing automation tools (HubSpot, Marketo)",
      "Background in global brand coordination",
    ],
    salary_min: 90000,
    salary_max: 120000,
    job_type: "onsite",
    category: "Marketing",
    posted_date: "2026-03-15",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-15",
    certification_tier: "core",
    skill_categories: ["marketing_ops", "campaign_management"],
    source_url: "#",
    benefits: ["Health insurance", "Employee discounts", "Flexible PTO"],
  },
  {
    id: "job-016",
    title: "Brand Marketing Manager",
    company: "Confidential",
    location: "Los Angeles, CA",
    description:
      "Inspired by the Mediterranean, our brand comes to life through iconic packaging and signature fragrance, for an exotic experience that transports the senses. Our original treatment pioneered oil-infused haircare and sparked global interest in argan oil. At the heart of our brand is the stylist community that inspires us to create effective and easy-to-use products.",
    responsibilities: [
      "Develop and execute brand marketing strategies for fragrance and beauty categories",
      "Collaborate with cross-functional teams including creative, sales, and retail partners",
      "Manage brand calendar and go-to-market planning",
      "Analyze market trends and competitive landscape to identify opportunities",
      "Build and maintain relationships with key retail and media partners",
    ],
    requirements: [
      "Bachelor's degree in Marketing, or a related field",
      "5+ years of Fragrance marketing experience required; preferably in luxury/premium categories",
      "Proficient in MS Office Suite (Word, Excel, PowerPoint)",
      "Strong analytical and communication skills",
      "Experience managing cross-functional projects and brand campaigns",
    ],
    preferred_qualifications: [
      "Experience in luxury or prestige beauty marketing",
      "Knowledge of the fragrance and personal care category",
    ],
    salary_min: 85000,
    salary_max: 115000,
    job_type: "onsite",
    category: "Marketing",
    posted_date: "2026-03-14",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-14",
    certification_tier: "core",
    skill_categories: ["brand_marketing", "product_marketing"],
    source_url: "#",
    benefits: ["Health insurance", "Employee discounts", "Learning budget"],
  },
  {
    id: "job-017",
    title: "Global Social Media Manager",
    company: "Confidential",
    location: "New York, NY",
    description:
      "The Manager, Global Social Media & Innovation will collaborate cross-functionally with regional social teams, e-commerce, paid media, and other key stakeholders to ensure global consistency while enabling locally relevant execution across markets. They will actively monitor the global social and competitive landscape.",
    responsibilities: [
      "Lead global content, community, and social commerce strategies across major social platforms",
      "Oversee daily content publishing and platform management across global social channels",
      "Manage global social content planning and asset coordination",
      "Monitor social trends, emerging platforms, and competitive activity",
      "Lead social reporting and analytics, delivering performance insights to internal teams",
    ],
    requirements: [
      "Lead global content, community, and social commerce strategies across major social platforms, overseeing official brand accounts",
      "Oversee daily content publishing and platform management across global social channels",
      "Manage global social content planning and asset coordination, including creative briefs and campaign support",
      "Monitor social trends, emerging platforms, and competitive activity",
      "Lead social reporting and analytics, delivering performance insights",
      "Manage and evolve global social commerce channels including TikTok",
    ],
    preferred_qualifications: [
      "Experience with social commerce and TikTok Shop",
      "Background in influencer marketing and creator partnerships",
    ],
    salary_min: 95000,
    salary_max: 125000,
    job_type: "onsite",
    category: "Marketing",
    posted_date: "2026-03-13",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-13",
    certification_tier: "core",
    skill_categories: ["social_media", "content_strategy", "analytics"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Flexible PTO"],
  },
  {
    id: "job-018",
    title: "Data Analyst",
    company: "Confidential",
    location: "Remote",
    description:
      "Always Build Trust. Say what you mean, mean what you say, and do what you say you're going to do. We are all owners. Never Stop Growing — change IS the constant. Stay hungry and curious. Be relentless in the pursuit of progress. Find a way — never settle, no excuses, nothing is impossible.",
    responsibilities: [
      "Collaborate with the Core Experience team to drive ideation and rigorous analysis of product experiments",
      "Partner with Product, Finance, and Operations to build and maintain robust reports and dashboards",
      "Write and optimize complex SQL queries to extract data from various sources",
      "Utilize Databricks and DBT to transform raw data into clean, accessible datasets",
      "Design and manage Tableau dashboards tracking key performance indicators for Investing and Banking features",
    ],
    requirements: [
      "Collaborate with the Core Experience team to drive ideation and rigorous analysis of product experiments",
      "Partner with Product, Finance, and Operations to build and maintain robust reports and dashboards",
      "Write and optimize complex SQL queries to extract data from various sources for deep-dive analysis",
      "Utilize Databricks and DBT to transform raw data into clean, accessible datasets",
      "Design and manage intuitive Tableau dashboards tracking key KPIs",
      "Monitor customer behavior and product performance using Amplitude",
    ],
    preferred_qualifications: [
      "Experience with Databricks and DBT",
      "Familiarity with fintech or banking products",
    ],
    salary_min: 90000,
    salary_max: 120000,
    job_type: "remote",
    category: "Data & Analytics",
    posted_date: "2026-03-15",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-15",
    certification_tier: "core",
    skill_categories: ["data_analysis", "sql", "tableau"],
    source_url: "#",
    benefits: ["Remote-first", "Health insurance", "Equity"],
  },
  {
    id: "job-019",
    title: "Data Analyst, Security Analytics",
    company: "Confidential",
    location: "Austin, TX",
    description:
      "The Analytics Platform & Enablement team is expanding its capabilities to strengthen data-driven decision-making across a global direct-to-consumer business serving over 400 million customers. We are looking for a Data Analyst who will play a key role in building scalable data solutions and uncovering actionable insights that drive marketing performance and business growth.",
    responsibilities: [
      "Build scalable data solutions and uncover actionable insights",
      "Drive marketing performance and business growth through data analysis",
      "Develop and maintain data visualizations using Tableau or Looker",
      "Apply SQL and Python/R for data extraction, transformation, and analysis",
      "Perform statistical analysis to inform business decisions",
    ],
    requirements: [
      "2+ years of data analysis experience",
      "Proficiency in SQL and Python or R",
      "Experience with data visualization tools (Tableau, Looker)",
      "Strong statistical analysis skills",
      "Ability to translate complex data into actionable business insights",
    ],
    preferred_qualifications: [
      "Experience with direct-to-consumer analytics",
      "Background in marketing analytics and attribution modeling",
    ],
    salary_min: 95000,
    salary_max: 125000,
    job_type: "onsite",
    category: "Data & Analytics",
    posted_date: "2026-03-14",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-14",
    certification_tier: "core",
    skill_categories: ["data_analysis", "sql", "python", "security_analytics"],
    source_url: "#",
    benefits: ["Health insurance", "Equity", "Learning budget"],
  },
  {
    id: "job-020",
    title: "Business Analyst",
    company: "Confidential",
    location: "New York, NY",
    description:
      "Elicit, analyze, and document business requirements (BRDs, FRDs, acceptance criteria, process flows). Partner with stakeholders to translate business needs into system requirements for PI products (e.g., DRG review, HBA, COB, data mining, IBR).",
    responsibilities: [
      "Elicit, analyze, and document business requirements (BRDs, FRDs, acceptance criteria, process flows)",
      "Partner with stakeholders to translate business needs into system requirements",
      "Manage claims processing workflows and related transactions",
      "Write and optimize SQL queries and Excel analyses for business reporting",
      "Manage competing priorities and deliver within deadlines",
    ],
    requirements: [
      "Education: Bachelor's degree in Business, Healthcare Administration, Data Analytics, or related field (or equivalent experience)",
      "3+ years as a Business Analyst in healthcare, payer, or PI environment",
      "Strong understanding of claims processing (professional, facility, pharmacy) and related transactions (837, 835, COB, EOBs)",
      "Strong analytical and problem-solving abilities",
      "Proficiency in SQL/Excel; familiarity with BI tools a plus",
      "Ability to manage competing priorities and deliver within deadlines",
    ],
    preferred_qualifications: [
      "Experience with healthcare payer systems",
      "Familiarity with BI tools (Tableau, Power BI)",
    ],
    salary_min: 85000,
    salary_max: 115000,
    job_type: "onsite",
    category: "Data & Analytics",
    posted_date: "2026-03-13",
    is_active: true,
    tpa_certification_preferred: false,
    apply_url: "#",
    experience_level: "mid",
    employer_confidential: true,
    verification_status: "verified",
    last_verified: "2026-03-13",
    certification_tier: "core",
    skill_categories: ["business_analysis", "sql", "healthcare"],
    source_url: "#",
    benefits: ["Health insurance", "Flexible PTO", "Learning budget"],
  },
];

export const screeningQuestions: ScreeningQuestion[] = [
  {
    id: "q1",
    type: "multiple_choice",
    question: "A role requires 'strong systems thinking.' Which response best demonstrates this?",
    options: [
      "I can follow established processes and documentation reliably",
      "I can identify how components interact and anticipate downstream effects of changes",
      "I have experience working at large companies with complex systems",
      "I prefer to work on isolated tasks rather than cross-functional projects",
    ],
    correctAnswer: 1,
  },
  {
    id: "q2",
    type: "multiple_choice",
    question: "You're asked to estimate timelines for a project with many unknowns. What's the most professional approach?",
    options: [
      "Give a precise date to show confidence",
      "Refuse to estimate until all requirements are defined",
      "Provide a range with clearly stated assumptions and risks",
      "Multiply your best guess by 3 without explaining why",
    ],
    correctAnswer: 2,
  },
  {
    id: "q3",
    type: "scenario",
    question: "Describe a time you identified a problem that wasn't assigned to you and took initiative to address it. What was the outcome?",
    rubric: "Should show proactive behavior, clear problem statement, measured response, and concrete result",
  },
  {
    id: "q4",
    type: "multiple_choice",
    question: "In a cross-functional team, stakeholders disagree on priorities. What's the most effective approach?",
    options: [
      "Escalate to leadership immediately",
      "Side with the most senior stakeholder",
      "Facilitate alignment by surfacing shared goals and making tradeoffs explicit",
      "Pause the project until everyone agrees",
    ],
    correctAnswer: 2,
  },
];

export function getJobById(id: string): Job | undefined {
  return mockJobs.find((job) => job.id === id);
}

export function getActiveJobs(): Job[] {
  return mockJobs.filter((job) => job.is_active);
}

export function searchJobs(
  query: string,
  filters?: {
    category?: string;
    job_type?: string;
    experience_level?: string;
    salary_min?: number;
    salary_max?: number;
  }
): Job[] {
  let jobs = getActiveJobs();

  if (query) {
    const q = query.toLowerCase();
    jobs = jobs.filter(
      (job) =>
        job.title.toLowerCase().includes(q) ||
        job.company.toLowerCase().includes(q) ||
        job.location.toLowerCase().includes(q) ||
        job.category.toLowerCase().includes(q)
    );
  }

  if (filters?.category) {
    jobs = jobs.filter((job) => job.category === filters.category);
  }

  if (filters?.job_type) {
    jobs = jobs.filter((job) => job.job_type === filters.job_type);
  }

  if (filters?.experience_level) {
    jobs = jobs.filter((job) => job.experience_level === filters.experience_level);
  }

  if (filters?.salary_min) {
    jobs = jobs.filter((job) => (job.salary_max ?? 0) >= filters.salary_min!);
  }

  if (filters?.salary_max) {
    jobs = jobs.filter((job) => (job.salary_min ?? 0) <= filters.salary_max!);
  }

  return jobs;
}
